Feature/setup project
mmsesay/school-library pull request #1
Opened 2021-12-13 22:56 UTC by mmsesay

In this PR I worked on the following:

- Add linter configurartions
- Add classes and their methods
- Update README.md file

2021-12-13 23:49 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @mmsesay,

Good job so far!
✔️ Good documentation
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-13 23:49 UTC, TedLivist commented on person.rb
> +    of_age || @parent_permission
- [ ] You have made a syntax error here that gives an **'undefined local variable or method'** error for of_age. You defined `of_age?` but you are calling `of_age` (without the question mark). Kindly fix this

2021-12-13 23:49 UTC, TedLivist commented on student.rb
> +  end
- [ ] Take a look at the image below. When I try to instantiate a Student object I get the error as shown in the image. Kindly fix this. (Hint: `classroom` can be the only `initialize` parameter; `age` can be the only parameter for `super`)

  ![mmesay-stud](https://user-images.githubusercontent.com/36542986/145904993-b925f161-236d-4131-a2a9-7e47fb5695c1.jpg)

2021-12-13 23:49 UTC, TedLivist commented on teacher.rb
> +
- [ ] I get the same error as in Student defined above when I try to instantiate a Teacher object. Kindly fix this.

  ![mmesay-teac](https://user-images.githubusercontent.com/36542986/145906725-d71dd652-32e9-4e69-b800-5f12f76127b6.jpg)

2021-12-14 08:58 UTC, arslanbisharat approved these changes
# Approved 👏 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

To Highlight: 
- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error is present. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project which you can see from your dashboard. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2021-12-14 09:02 UTC, merged